### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [z3bra/wendy#1]
Dear @z3bra ,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by z3bra** [comment]
Thanks for your interest in wendy. That is not possible however.
Wendy uses the inotify lib internally, which is a Linux-only feature. It cannot, by design, run on windows.

**Comment by sergeevabc** [comment]
Thank you for a quick reply, @z3bra.
